import { OrderStatus, ServiceType } from '@/types/order';
import { UserProfile } from '@/types/user';
import { Laundry, LaundryService } from '@/types/laundry';

export const ORDER_STATUS_CONFIG: Record<
  OrderStatus,
  { label: string; description: string; color: string; bg: string; stepIndex: number }
> = {
  pending: {
    label: 'Menunggu Konfirmasi',
    description: 'Pesanan telah dibuat dan menunggu penugasan kurir.',
    color: 'text-amber-700',
    bg: 'bg-amber-50 border-amber-200',
    stepIndex: 0,
  },
  assigned: {
    label: 'Kurir Ditugaskan',
    description: 'Kurir sedang dalam perjalanan menuju lokasi penjemputan.',
    color: 'text-sky-700',
    bg: 'bg-sky-50 border-sky-200',
    stepIndex: 1,
  },
  picked_up: {
    label: 'Pakaian Diambil',
    description: 'Pakaian telah diambil kurir dan dibawa ke workshop laundry.',
    color: 'text-indigo-700',
    bg: 'bg-indigo-50 border-indigo-200',
    stepIndex: 2,
  },
  in_washing: {
    label: 'Dalam Proses Cuci',
    description: 'Pakaian sedang dicuci, dikeringkan, dan disetrika dengan higienis.',
    color: 'text-blue-700',
    bg: 'bg-blue-50 border-blue-200',
    stepIndex: 3,
  },
  ready_for_delivery: {
    label: 'Siap Diantar',
    description: 'Pakaian telah bersih, rapi, terkemas dan siap diantarkan kembali.',
    color: 'text-teal-700',
    bg: 'bg-teal-50 border-teal-200',
    stepIndex: 4,
  },
  out_for_delivery: {
    label: 'Kurir Mengantar',
    description: 'Kurir sedang dalam perjalanan mengantarkan paket laundry Anda.',
    color: 'text-purple-700',
    bg: 'bg-purple-50 border-purple-200',
    stepIndex: 5,
  },
  delivered: {
    label: 'Selesai & Diterima',
    description: 'Laundry telah diterima dengan selamat. Terima kasih telah memesan!',
    color: 'text-emerald-700',
    bg: 'bg-emerald-50 border-emerald-200',
    stepIndex: 6,
  },
  cancelled: {
    label: 'Dibatalkan',
    description: 'Pesanan ini telah dibatalkan.',
    color: 'text-rose-700',
    bg: 'bg-rose-50 border-rose-200',
    stepIndex: -1,
  },
};

export const ORDER_TIMELINE_STEPS = [
  { key: 'pending', label: 'Pesanan Dibuat' },
  { key: 'assigned', label: 'Kurir Ditugaskan' },
  { key: 'picked_up', label: 'Penjemputan' },
  { key: 'in_washing', label: 'Proses Cuci' },
  { key: 'ready_for_delivery', label: 'Siap Diantar' },
  { key: 'out_for_delivery', label: 'Pengantaran' },
  { key: 'delivered', label: 'Selesai' },
];

export interface ExtendedLaundry extends Laundry {
  distanceKm: number;
  startingPrice: number;
  estPickupMinutes: number;
  badge?: 'Recommended' | 'Fast Pickup' | 'Premium' | 'Promo' | 'Buka 24 Jam';
}

export const DEMO_LAUNDRIES: ExtendedLaundry[] = [
  {
    id: 'lnd_001',
    code: 'LND-KB45',
    name: 'FreshWash Express Kebayoran',
    ownerId: 'usr_owner_01',
    ownerName: 'Hendra Wijaya',
    description: 'Layanan laundry higienis premium cabang Kebayoran Baru dengan jaminan pelembut bunga sakura dan pengeringan anti-bakteri.',
    phone: '081122334455',
    address: 'Jl. Ahmad Dahlan No. 12, Kebayoran Baru, Jakarta Selatan',
    latitude: -6.2415,
    longitude: 106.7972,
    openingTime: '08:00',
    closingTime: '21:00',
    isOpen: true,
    isActive: true,
    verificationStatus: 'verified',
    rating: 4.9,
    totalReviews: 128,
    distanceKm: 1.2,
    startingPrice: 8000,
    estPickupMinutes: 25,
    badge: 'Recommended',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'lnd_002',
    code: 'LND-TB88',
    name: 'CleanPro Laundry Tebet',
    ownerId: 'usr_owner_02',
    ownerName: 'Bambang Sukoco',
    description: 'Spesialis cuci kiloan super cepat, setrikau uap wangi tahan lama, serta perawatan sepatu dan helm profesional.',
    phone: '081299887766',
    address: 'Jl. Tebet Raya No. 45, Tebet, Jakarta Selatan',
    latitude: -6.2289,
    longitude: 106.8525,
    openingTime: '07:30',
    closingTime: '21:00',
    isOpen: true,
    isActive: true,
    verificationStatus: 'verified',
    rating: 4.8,
    totalReviews: 95,
    distanceKm: 2.5,
    startingPrice: 7000,
    estPickupMinutes: 15,
    badge: 'Fast Pickup',
    createdAt: '2026-08-02T09:00:00Z',
  },
  {
    id: 'lnd_003',
    code: 'LND-SN10',
    name: 'SilkCare Dry Clean Senopati',
    ownerId: 'usr_owner_03',
    ownerName: 'Diana Sastro',
    description: 'Boutique dry cleaning khusus jas pengantin, gaun pesta, batik sutra, dan pakaian branded dengan solvent impor eropa.',
    phone: '081377665544',
    address: 'Jl. Senopati No. 88, Kebayoran Baru, Jakarta Selatan',
    latitude: -6.2341,
    longitude: 106.8083,
    openingTime: '09:00',
    closingTime: '20:00',
    isOpen: true,
    isActive: true,
    verificationStatus: 'verified',
    rating: 5.0,
    totalReviews: 64,
    distanceKm: 3.1,
    startingPrice: 40000,
    estPickupMinutes: 35,
    badge: 'Premium',
    createdAt: '2026-08-03T10:00:00Z',
  },
  {
    id: 'lnd_004',
    code: 'LND-PC12',
    name: 'Berkah Eco Laundry Pancoran',
    ownerId: 'usr_owner_04',
    ownerName: 'Achmad Fauzi',
    description: 'Laundry ramah lingkungan menggunakan deterjen biodegradable aman kulit sensitif. Harga paling hemat se-Jakarta Selatan.',
    phone: '081566778899',
    address: 'Jl. Pancoran Barat No. 14, Pancoran, Jakarta Selatan',
    latitude: -6.2512,
    longitude: 106.8341,
    openingTime: '07:00',
    closingTime: '21:30',
    isOpen: true,
    isActive: true,
    verificationStatus: 'verified',
    rating: 4.7,
    totalReviews: 210,
    distanceKm: 4.0,
    startingPrice: 6000,
    estPickupMinutes: 30,
    badge: 'Promo',
    createdAt: '2026-08-04T11:00:00Z',
  },
  {
    id: 'lnd_005',
    code: 'LND-GD24',
    name: 'SuperWash 24 Hours Gandaria',
    ownerId: 'usr_owner_05',
    ownerName: 'Rian Perdana',
    description: 'Siap melayani pickup & delivery 24 jam nonstop. Layanan cuci super kilat 3 jam selesai langsung diantar.',
    phone: '081788990011',
    address: 'Jl. Gandaria Tengah II No. 5, Kebayoran Baru, Jakarta Selatan',
    latitude: -6.2488,
    longitude: 106.7892,
    openingTime: '00:00',
    closingTime: '23:59',
    isOpen: true,
    isActive: true,
    verificationStatus: 'verified',
    rating: 4.6,
    totalReviews: 88,
    distanceKm: 1.8,
    startingPrice: 18000,
    estPickupMinutes: 20,
    badge: 'Buka 24 Jam',
    createdAt: '2026-08-05T12:00:00Z',
  },
];

export type ServiceCatalogItem = LaundryService & {
  price: number;
  type?: ServiceType;
  popular?: boolean;
  badge?: string;
  minOrder?: string;
  estimatedTime?: string;
};

export const SERVICE_CATALOG: ServiceCatalogItem[] = [
  // Services for Laundry 1: FreshWash Express Kebayoran (lnd_001)
  {
    id: 'srv_001',
    laundryId: 'lnd_001',
    code: 'kiloan',
    type: 'kiloan',
    name: 'Cuci Komplit Kiloan',
    description: 'Cuci bersih, pelembut sakura, pengeringan higienis, dan setrika rapi.',
    pricingType: 'per_kg',
    price_per_unit: 8000,
    price: 8000,
    unit: 'kg',
    minWeight: 3,
    estimatedHours: 48,
    estimatedTime: '2-3 Hari',
    minOrder: '3 kg',
    iconName: 'ShoppingBag',
    popular: true,
    badge: 'Paling Laris',
    isActive: true,
  },
  {
    id: 'srv_002',
    laundryId: 'lnd_001',
    code: 'express',
    type: 'express',
    name: 'Express 6 Jam',
    description: 'Layanan super cepat selesai dalam 6 jam. Prioritas penjemputan utama!',
    pricingType: 'per_kg',
    price_per_unit: 15000,
    price: 15000,
    unit: 'kg',
    minWeight: 3,
    estimatedHours: 6,
    estimatedTime: '6 Jam',
    minOrder: '3 kg',
    iconName: 'Zap',
    popular: false,
    badge: 'Super Cepat',
    isActive: true,
  },
  {
    id: 'srv_003',
    laundryId: 'lnd_001',
    code: 'dry_clean',
    type: 'dry_clean',
    name: 'Dry Cleaning Jas & Gaun',
    description: 'Perawatan khusus jas formal, gaun pesta, batik sutra, dan pakaian mewah.',
    pricingType: 'per_item',
    price_per_unit: 35000,
    price: 35000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 36,
    estimatedTime: '1-2 Hari',
    minOrder: '1 pcs',
    iconName: 'Sparkles',
    popular: false,
    badge: 'Perawatan Premium',
    isActive: true,
  },
  {
    id: 'srv_004',
    laundryId: 'lnd_001',
    code: 'satuan',
    type: 'satuan',
    name: 'Cuci Bedcover & Sprei',
    description: 'Bedcover, karpet, sepatu, sprei, dan tas dengan penanganan khusus higienis.',
    pricingType: 'per_item',
    price_per_unit: 25000,
    price: 25000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 48,
    estimatedTime: '2 Hari',
    minOrder: '1 pcs',
    iconName: 'Box',
    popular: false,
    badge: 'Barang Besar',
    isActive: true,
  },

  // Services for Laundry 2: CleanPro Laundry Tebet (lnd_002)
  {
    id: 'srv_101',
    laundryId: 'lnd_002',
    code: 'kiloan',
    type: 'kiloan',
    name: 'Cuci Kiloan CleanPro',
    description: 'Pencucian pakaian harian dengan deterjen anti-bakteri dan wangi lavender.',
    pricingType: 'per_kg',
    price_per_unit: 7000,
    price: 7000,
    unit: 'kg',
    minWeight: 3,
    estimatedHours: 48,
    estimatedTime: '2 Hari',
    minOrder: '3 kg',
    iconName: 'ShoppingBag',
    popular: true,
    badge: 'Super Hemat',
    isActive: true,
  },
  {
    id: 'srv_102',
    laundryId: 'lnd_002',
    code: 'express',
    type: 'express',
    name: 'Setrika Uap Kiloan',
    description: 'Layanan setrika rapi menggunakan setrika uap uap boiler tanpa cuci.',
    pricingType: 'per_kg',
    price_per_unit: 5000,
    price: 5000,
    unit: 'kg',
    minWeight: 3,
    estimatedHours: 24,
    estimatedTime: '1 Hari',
    minOrder: '3 kg',
    iconName: 'Zap',
    popular: false,
    badge: 'Setrika Rapi',
    isActive: true,
  },
  {
    id: 'srv_103',
    laundryId: 'lnd_002',
    code: 'satuan',
    type: 'satuan',
    name: 'Cuci Sepatu & Helm',
    description: 'Deep cleaning sepatu sneakers, kulit, heels, dan helm sepeda/motor.',
    pricingType: 'per_item',
    price_per_unit: 30000,
    price: 30000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 48,
    estimatedTime: '2 Hari',
    minOrder: '1 pcs',
    iconName: 'Box',
    popular: true,
    badge: 'Paling Dicari',
    isActive: true,
  },

  // Services for Laundry 3: SilkCare Dry Clean Senopati (lnd_003)
  {
    id: 'srv_201',
    laundryId: 'lnd_003',
    code: 'dry_clean',
    type: 'dry_clean',
    name: 'Dry Clean Jas & Tuxedo',
    description: 'Pembersihan dry clean solvent eropa khusus jas formal & tuxedo pengantin.',
    pricingType: 'per_item',
    price_per_unit: 40000,
    price: 40000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 24,
    estimatedTime: '1 Hari',
    minOrder: '1 pcs',
    iconName: 'Sparkles',
    popular: true,
    badge: 'Boutique Care',
    isActive: true,
  },
  {
    id: 'srv_202',
    laundryId: 'lnd_003',
    code: 'dry_clean',
    type: 'dry_clean',
    name: 'Dry Clean Gaun Pesta',
    description: 'Perawatan gaun pesta, dress payet, dan gaun pengantin dengan steamer khusus.',
    pricingType: 'per_item',
    price_per_unit: 60000,
    price: 60000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 48,
    estimatedTime: '2 Hari',
    minOrder: '1 pcs',
    iconName: 'Sparkles',
    popular: false,
    badge: 'Special Treatment',
    isActive: true,
  },
  {
    id: 'srv_203',
    laundryId: 'lnd_003',
    code: 'dry_clean',
    type: 'dry_clean',
    name: 'Dry Clean Batik Sutra',
    description: 'Perawatan kain batik tulis sutra asli agar warna tidak pudar dan kain terjaga.',
    pricingType: 'per_item',
    price_per_unit: 45000,
    price: 45000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 24,
    estimatedTime: '1 Hari',
    minOrder: '1 pcs',
    iconName: 'Sparkles',
    popular: false,
    badge: 'Warisan Klasik',
    isActive: true,
  },

  // Services for Laundry 4: Berkah Eco Laundry Pancoran (lnd_004)
  {
    id: 'srv_301',
    laundryId: 'lnd_004',
    code: 'kiloan',
    type: 'kiloan',
    name: 'Cuci Kiloan Eco Hemat',
    description: 'Cuci bersih ramah lingkungan dengan harga ekonomis se-Jakarta Selatan.',
    pricingType: 'per_kg',
    price_per_unit: 6000,
    price: 6000,
    unit: 'kg',
    minWeight: 3,
    estimatedHours: 48,
    estimatedTime: '2 Hari',
    minOrder: '3 kg',
    iconName: 'ShoppingBag',
    popular: true,
    badge: 'Termurah',
    isActive: true,
  },
  {
    id: 'srv_302',
    laundryId: 'lnd_004',
    code: 'satuan',
    type: 'satuan',
    name: 'Cuci Bedcover Jumbo',
    description: 'Pencucian bedcover king/queen size dengan pengeringan ekstra panas.',
    pricingType: 'per_item',
    price_per_unit: 25000,
    price: 25000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 48,
    estimatedTime: '2 Hari',
    minOrder: '1 pcs',
    iconName: 'Box',
    popular: false,
    badge: 'Bersih Tuntas',
    isActive: true,
  },
  {
    id: 'srv_303',
    laundryId: 'lnd_004',
    code: 'satuan',
    type: 'satuan',
    name: 'Cuci Sprei & Selimut',
    description: 'Cuci sprei dan selimut tebal dengan disinfektan bebas kuman.',
    pricingType: 'per_item',
    price_per_unit: 15000,
    price: 15000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 24,
    estimatedTime: '1 Hari',
    minOrder: '1 pcs',
    iconName: 'Box',
    popular: false,
    badge: 'Wangi Segar',
    isActive: true,
  },

  // Services for Laundry 5: SuperWash 24 Hours Gandaria (lnd_005)
  {
    id: 'srv_401',
    laundryId: 'lnd_005',
    code: 'express',
    type: 'express',
    name: 'Cuci Kilat 3 Jam',
    description: 'Layanan ultra kilat 3 jam selesai! Langsung diantar kapan pun Anda butuh.',
    pricingType: 'per_kg',
    price_per_unit: 20000,
    price: 20000,
    unit: 'kg',
    minWeight: 3,
    estimatedHours: 3,
    estimatedTime: '3 Jam Selesai',
    minOrder: '3 kg',
    iconName: 'Zap',
    popular: true,
    badge: 'Super Kilat',
    isActive: true,
  },
  {
    id: 'srv_402',
    laundryId: 'lnd_005',
    code: 'satuan',
    type: 'satuan',
    name: 'Cuci Karpet & Matras',
    description: 'Pembersihan karpet lantai dan matras gulung dengan vacuum extractor.',
    pricingType: 'per_item',
    price_per_unit: 18000,
    price: 18000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 48,
    estimatedTime: '2 Hari',
    minOrder: '1 pcs',
    iconName: 'Box',
    popular: false,
    badge: 'Bebas Debu',
    isActive: true,
  },
  {
    id: 'srv_403',
    laundryId: 'lnd_005',
    code: 'satuan',
    type: 'satuan',
    name: 'Cuci Stroller & Box Bayi',
    description: 'Pembersihan steril bahan organik khusus stroller bayi dan carseat.',
    pricingType: 'per_item',
    price_per_unit: 45000,
    price: 45000,
    unit: 'pcs',
    minWeight: 1,
    estimatedHours: 48,
    estimatedTime: '2 Hari',
    minOrder: '1 pcs',
    iconName: 'Box',
    popular: false,
    badge: 'Aman Bayi',
    isActive: true,
  },
];

export const TIME_SLOTS = [
  '08:00 - 10:00 WIB',
  '11:00 - 14:00 WIB',
  '15:00 - 17:00 WIB',
];

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'usr_customer_01',
    email: 'budi@customer.com',
    fullName: 'Budi Santoso',
    phone: '081234567890',
    role: 'customer',
    address: 'Jl. Melati No. 45, Kebayoran Baru, Jakarta Selatan',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr_courier_01',
    email: 'agung@courier.com',
    fullName: 'Agung Pratama (Kurir 1)',
    phone: '089876543210',
    role: 'courier',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr_courier_02',
    email: 'rizky@courier.com',
    fullName: 'Rizky Courier (Kurir 2)',
    phone: '089911223344',
    role: 'courier',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr_owner_01',
    email: 'hendra@laundry.com',
    fullName: 'Hendra Wijaya (Pemilik Mitra Laundry)',
    phone: '081122334455',
    role: 'laundry_owner',
    laundryId: 'lnd_001',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr_staff_01',
    email: 'maya@laundry.com',
    fullName: 'Maya Staf Operasional',
    phone: '081122334466',
    role: 'laundry_staff',
    laundryId: 'lnd_001',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr_admin_01',
    email: 'admin@freshlaundry.com',
    fullName: 'Siti Admin Platform',
    phone: '081122334477',
    role: 'platform_admin',
    createdAt: '2026-08-01T10:00:00Z',
  },
];
